### ISSUE TITLE
JSON format?

### ISSUE THREAD

**Issue by leegee** [leinonen/cucumber-html-report#12]
What format JSON is expected?

My tests run through `protractor-cucumber-framework`, which as far as I can tell, allows `cucumberjs` to output its JSON as it always does. But it seems it cannot be parsed:

```bash
$protractor --tags @tagX --name "Scenario X"
```
...
```bash
Failing scenarios:
features\portfolio.feature:43 # Scenario: With a collapsed 4-entry portfolio

1 scenario (1 failed)
19 steps (1 failed, 2 skipped, 16 passed)
0m17.590s

$ node lib/html-report.js
D:\src\product\node_modules\cucumber-html-report\summary.js:11
    return sum(feature.elements.map(elementCallback));
                               ^

TypeError: Cannot read property 'map' of undefined
    at D:\src\product\node_modules\cucumber-html-report\summary.js:11:32
    at Array.map (native)
    at sumFeatures (D:\src\product\node_modules\cucumber-html-report\summary.js:9:23)
    at stepSum (D:\src\product\node_modules\cucumber-html-report\summary.js:22:10)
    at Object.exports.calculateSummary (D:\src\product\node_modules\cucumber-html-report\summary.js:36:21)
    at CucumberHtmlReport.createReport (D:\src\product\node_modules\cucumber-html-report\index.js:41:22)
    at Object.<anonymous> (D:\src\product\test\e2e\lib\html-report.js:12:8)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)

$ cat ../../reports/e2e/e2e-report.json
[
  {
    "description": "With a collapsed 4-entry portfolio",
    "assertions": [
      {
        "passed": true
      },
      {
        "passed": true
      },
      {
        "passed": true
      },
      {
        "passed": true
      },
      {
        "passed": true
      },
      {
        "passed": true
      },
      {
        "passed": true
      },
      {
        "passed": true
      },
      {
        "passed": true
      },
      {
        "passed": true
      },
      {
        "passed": true
      },
      {
        "passed": true
      },
      {
        "passed": true
      },
      {
        "passed": true
      },
      {
        "passed": true
      },
      {
        "passed": true
      },
      {
        "passed": false,
        "errorMsg": "At least some of the text sent to the grid was found in grid: expected '' to have a length above 0 but got 0",
        "stackTrace": "AssertionError: At least some of the text sent to the grid was found in grid: expected '' to have a length above 0 but got 0\n    at D:\\src\\product\\test\\e2e\\step-definitions\\keyboard.spec.js:112:97\n    at Promise.invokeCallback_ (C:\\Users\\lee\\AppData\\Roaming\\npm\\node_modules\\protractor\\node_modules\\selenium-webdriver\\lib\\promise.js:1329:14)\n    at TaskQueue.execute_ (C:\\Users\\lee\\AppData\\Roaming\\npm\\node_modules\\protractor\\node_modules\\selenium-webdriver\\lib\\promise.js:2790:14)\n    at TaskQueue.executeNext_ (C:\\Users\\lee\\AppData\\Roaming\\npm\\node_modules\\protractor\\node_modules\\selenium-webdriver\\lib\\promise.js:2773:21)\n    at C:\\Users\\lee\\AppData\\Roaming\\npm\\node_modules\\protractor\\node_modules\\selenium-webdriver\\lib\\promise.js:2652:27\n    at C:\\Users\\lee\\AppData\\Roaming\\npm\\node_modules\\protractor\\node_modules\\selenium-webdriver\\lib\\promise.js:639:7\n    at process._tickCallback (node.js:379:9)"
      },
      {
        "passed": true
      }
    ],
    "duration": null
  }
]
lee@DESKTOP-X MINGW64 /d/src/product/test/e2e (protractor-cucumber)
$ cat lib/html-report.js
const Report = require('cucumber-html-report'),
        path = require('path');

var options = {
        source:  path.join(__dirname, '../../../reports/e2e/e2e-report.json'), // cucumber-json-for-html
        dest: './',
        name: 'temp.html'
        // template: 'mytemplate.html' // your custom mustache template (uses default if not specified)
};

var report = new Report(options);
report.createReport();
lee@DESKTOP-X MINGW64 /d/src/product/test/e2e (protractor-cucumber)
$
```

**Comment by leinonen** [comment]
Well, we use it at work to generate reports from protractor (testing angular applications) with cucumber.
Let me get back to you with a more "complete" example..

Maybe we can work something out to match our needs..

**Comment by leinonen** [comment]
An example json file:
`[
  {
    "id": "Ping",
    "name": "Ping",
    "description": "As a user\r\nI must be able to ping the application\r\nto ensure all is set up properly",
    "line": 2,
    "keyword": "Feature",
    "tags": [
      {
        "name": "@ping",
        "line": 1
      }
    ],
    "uri": "ping.feature",
    "elements": [
      {
        "name": "Successful ping",
        "id": "Ping;successful-ping",
        "line": 7,
        "keyword": "Scenario",
        "description": "",
        "type": "scenario",
        "steps": [
          {
            "keyword": "Before ",
            "hidden": true,
            "result": {
              "duration": 5927652289,
              "status": "passed"
            },
            "match": {}
          },
          {
            "name": "I ping",
            "line": 8,
            "keyword": "When ",
            "result": {
              "duration": 238664314,
              "status": "passed"
            },
            "match": {}
          },
          {
            "name": "I should get a pong",
            "line": 9,
            "keyword": "Then ",
            "result": {
              "duration": 1073883228,
              "status": "passed"
            },
            "match": {}
          },
          {
            "keyword": "After ",
            "hidden": true,
            "result": {
              "duration": 42631,
              "status": "passed"
            },
            "match": {}
          },
          {
            "keyword": "After ",
            "hidden": true,
            "result": {
              "duration": 1003062744,
              "status": "passed"
            },
            "match": {}
          }
        ]
      }
    ]
  }
]`

**Comment by leegee** [comment]
It does now process my protractor-cucumber output, but the default template seems to incorrectly process. 

![fireshot capture 34 - cucumber report - http___localhost_3000_reports_e2e_report-temp html](https://cloud.githubusercontent.com/assets/512816/15172551/a980bb90-174e-11e6-953d-bead11378f66.png)

[e2e-report.json.txt](https://github.com/leinonen/cucumber-html-report/files/258722/e2e-report.json.txt)

**Comment by leegee** [comment]
Fine now, thank you!
