### ISSUE TITLE
Failed test not shown in report, but screenshot is

### ISSUE THREAD

**Issue by hrietman** [leinonen/cucumber-html-report#16]
Hi,

When using this framework I noticed on a failed test it does have a screenshot in the report but the step that caused it is not colored red. 

Going through the code it seems that for some reason the failed step information is filtered out. The information is in the before "keyword" element of the cucumber_report.json.

Any idea's?

**Comment by leinonen** [comment]
I'll look into it..

**Comment by leinonen** [comment]
Hello, can you try again with version 0.3.2?

**Comment by hrietman** [comment]
Works as expected, many thanks!

**Comment by hrietman** [comment]
Just one remark, the number of failed tests on top of the page indicates always zero, even if there are test failures. The test failure is displayed correct, with screenshot and stacktrace.

**Comment by leinonen** [comment]
Will look into it :)
