### ISSUE TITLE
empty background step will prevent report generation

### ISSUE THREAD

**Issue by cartoloupe** [leinonen/cucumber-html-report#17]
If a feature file like this is processed:

```
Feature: Some thing
  As a User
  
  Background:

  Scenario: Something else
    Given login
```

the reporter will crash with:
```
TypeError: Cannot read property 'filter' of undefined
    at /Users/cartoloupe/repos/test_suite/node_modules/cucumber-html-report/index.js:127:38
    at Array.forEach (native)
    at processScenarios (/Users/cartoloupe/repos/test_suite/node_modules/cucumber-html-report/index.js:118:15)
```

because the background has no steps:
```
{ keyword: 'Background',
  name: '',
  description: '',
  line: 8,
  type: 'background',
  before: [ { match: [Object], result: [Object] } ] }
```

However, this feature file is able to run in cucumber 2.3.0.

This crash helped me catch the empty Background step, and I deleted it, but, maybe the error message can be improved, or handled/ignored.

Also, thanks for this reporting system!

**Comment by leinonen** [comment]
Glad you like it.

Can you test if version 0.3.4 solves this? Otherwise can you provide an example json? 
Because I was unable to reproduce the error when adding a Background element to my feature file.

**Comment by cartoloupe** [comment]
Good call, I tested it 0.3.4 and it works fine 👍
