### ISSUE TITLE
failure in background will skip scenario

### ISSUE THREAD

**Issue by cartoloupe** [leinonen/cucumber-html-report#18]
If a failure happens in a Background step, then the following Scenario will be skipped.

This can throw off calculations; e.g.

![screen shot 2016-06-10 at 12 32 36 am](https://cloud.githubusercontent.com/assets/4593934/15954264/df85aa28-2ea2-11e6-9b41-327d2088bde5.png)

there is a 5th failing scenario above, but it just happened to fail in the background step.

It looks like scenarios are taken to be all elements of the feature (`var scenarios = feature.elements;` in `index.js`). This will include background elements as well.

Maybe here's one way to figure out if an entire scenario was skipped (and failed):
- in `summary.js`, some metrics are calculated for each scenario:
```
function getScenarioResult(scenario) {
  return {
    numSteps:    getNumStepsForScenario(scenario),
    passedSteps: getNumPassedStepsForScenario(scenario),
    failedSteps: getNumFailedStepsForScenario(scenario)
  };
}
```

- in addition to the above metrics, the number of skipped steps could also be calculated (`skippedSteps`)
- if `skippedSteps` is equal to `numSteps`, then the scenario was never hit, which implies that something went wrong in the background step. If this is the case, set the scenario status to failed.

Let me know your thoughts, I would love to help out with a PR.

**Comment by leinonen** [comment]
Please open a Pull Request, as I would love if you could fix that :)
