### ISSUE TITLE
option to only display failures

### ISSUE THREAD

**Issue by cartoloupe** [leinonen/cucumber-html-report#19]
In some situations, there could be 500 or so tests, which over a period of maintenance have a relatively low failure rate (e.g. 30 failures, or even 5 failures). 

In this case, it would be helpful to just view the failures and their stack traces.

This could probably be satisfied by grouping the failures and displaying them at the top of the report, and having a switch to toggle between layouts.

**Comment by leinonen** [comment]
I will implement that feature soon, as many people have requested it. Thanks for your input.

**Comment by leinonen** [comment]
Version 0.5.0 will show failing features and scenarios first. Note: new api, see README
