### ISSUE TITLE
Test Coverage: image embedding

### ISSUE THREAD

**Issue by leegee** [leinonen/cucumber-html-report#23]
Test image embedding with utf8 characters, which ought to be replaced.

(Love the new report format, btw! Thanks)

**Comment by leinonen** [comment]
Glad you like the new format :)

**Comment by leinonen** [comment]
Can you try version 0.3.6? I now slugify the filenames, and it is supposed to handle utf8 characters.

**Comment by leinonen** [comment]
Status?

**Comment by leegee** [comment]
I'm off my protractor contract, taking some time ...

**Comment by leinonen** [comment]
Ok, have fun!
