### ISSUE TITLE
Allow select-and-copy of from error output

### ISSUE THREAD

**Issue by leegee** [leinonen/cucumber-html-report#24]
ATM, touching the error output folds it up -- but I'd like to get it, or some of it, onto my clipboard.

I'm happy to write the code, but what would be a good solution?

http://stackoverflow.com/a/30810322/418150

**Comment by leinonen** [comment]
Not sure. If you find a good solution, feel free to implement it :)
document.execCommand seems good enough for me, but it might not work for others..
What do you think?

**Comment by leinonen** [comment]
Nice!
