### ISSUE TITLE
Feature Request: include datatables in output

### ISSUE THREAD

**Issue by leegee** [leinonen/cucumber-html-report#25]
it might be just me who requires this....

**Comment by leinonen** [comment]
Feel free to implement this ;)

**Comment by leegee** [comment]
https://github.com/leinonen/cucumber-html-report/pull/27

**Comment by leinonen** [comment]
Thank you for your contribution! I have released version 0.3.7.

**Comment by leegee** [comment]
Thank you for the excellent module!
