### ISSUE TITLE
Feature Request : Include plain text imbeddings in output

### ISSUE THREAD

**Issue by ChristopherFry** [leinonen/cucumber-html-report#30]
Similar to https://github.com/leinonen/cucumber-html-report/issues/25, I would like to output mime types of text/plain to the report.  I can implement this if you like the idea.

**Comment by leinonen** [comment]
Please do :)

**Comment by leinonen** [comment]
Thanks. I have published version 0.3.8

**Comment by ChristopherFry** [comment]
Thanks!
