### ISSUE TITLE
Q: Would it be possible to move to handlebars for handling templates?

### ISSUE THREAD

**Issue by fpanwaskar** [leinonen/cucumber-html-report#40]
The fact that the plugin offers the ability to have custom templates is great.  The only thing is that Mustache is a bit limited in what can be done with the model in the template.

It would give users more flexibility if we could use handlebars as they could have more complex conditions on the page.

Is this reasonable?  I'm happy to make the change in PR and test.

**Comment by leinonen** [comment]
Yes, why not :) Flexibility is always great. I'd be happy if you implement it!

**Comment by revathyvarma** [comment]
Where do we have to add this code for the reporter?Is it in the config?
