### ISSUE TITLE
Doesnot convert big json file into html

### ISSUE THREAD

**Issue by Galileo1** [leinonen/cucumber-html-report#46]
Hi,

It seems so that this is not converting big json files into html? 
In my case small json files are converted to html like a charm but big json files couldn't .Any clue?

Cheers

**Comment by leinonen** [comment]
How big?

Den sön 14 aug. 2016 23:05Galileo1 <notifications@github.com> skrev:

**Comment by Galileo1** [comment]
Hi, 

I am sorry I think the problem is something else. I am using cucumber/protractor framework and I ma taking screenshot after scenario fails.It seems that taking screenshots and convert the base64 to string("binary") is throwing error([9540:37976:0815/091834:ERROR:latency_info.cc(163)] RenderWidgetHostImpl::OnSwapCompositorFrame, LatencyInfo vector size 245 is too big.) for one of the scenario.I am using buffer(new Buffer(base64png, 'base64').toString('binary')) , ithink it is not sufficient.

If you have any clue please let me know otherwise I will close this.Apologies for false alarm.

Cheers

**Comment by leinonen** [comment]
Seems like something else is the problem.. like grabbing the screenshot.

Den sön 14 aug. 2016 23:35Galileo1 <notifications@github.com> skrev:

**Comment by Galileo1** [comment]
yeah .Thanks anyways.Closing this issue.
