### ISSUE TITLE
Reporter fails when using custom options

### ISSUE THREAD

**Issue by ndelrossi** [leinonen/cucumber-html-report#55]
I've been using this module for a while providing custom options for my source file name. This has broken recently in that it now expects a specific file name.

I created a very simple test with these options which fails now but was working on 0.4.4 and back.

```javascript
var options = {
    source:    'report.json',
    dest:      './',
    name:      'report.html',
    title:     'Cucumber Report'
};
```

produces this error:
```
Input file ./cucumber_report.json does not exist! Aborting
Config error
/Users/redacted/Dev/test-reporter/test.js:9
var report = new Report(options);
             ^

TypeError: Report is not a constructor
    at Object.<anonymous> (/Users/redacted/Dev/test-reporter/test.js:9:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

The breaking change is in this commit: https://github.com/leinonen/cucumber-html-report/commit/9b5bae6f8ce3f3b66a86e04c91f3098718a93ca5

**Comment by leinonen** [comment]
Sorry, I am working on it. There have been some major commits to this repo. Need some time to clean up and fix stuff. Sorry if this is causing you problems. Stay tuned for a new release soon.

**Comment by ndelrossi** [comment]
No worries. I locked to version 0.4.4. Thank you for working on this tool. It is great :)

**Comment by leinonen** [comment]
Please test version 0.5.0

**Comment by leinonen** [comment]
Try the latest version.
