### ISSUE TITLE
Does not default to index.html when 'name' is not provided in create function's options object.

### ISSUE THREAD

**Issue by eis95** [leinonen/cucumber-html-report#64]
var CucumberHtmlReport = require('cucumber-html-report');

            return CucumberHtmlReport.create({

                source: sourceJson, // source json

                dest: outputDir // target directory (will create if not exists)

            });

(node:8976) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Template name undefined does not valid! Aborting

**Comment by leinonen** [comment]
I have resolved the issue in version 0.5.6
