### ISSUE TITLE
Failing After or Before hook should render the Scenario failed

### ISSUE THREAD

**Issue by thevictor13** [leinonen/cucumber-html-report#69]
When all the user-defined steps are passing but there is an after hook with a status of "failed", the Scenario is still marked as passed, which in fact should be marked as failing.

Here's an example failing After step from the `report.json`:
```
{
    "keyword": "After ",
    "hidden": true,
    "result": {
        "status": "failed",
        "duration": 13338271,
        "error_message": "Error: Console errors"
    },
    "match": {}
}
```
The problem is that you're classing all hidden or nameless steps as invalid steps. But when such a step fails, the report completely ignores that due to this.
To circumvent this problem, I have modified the source to only ignore hidden steps when they're not failing. This has a side effect though - if a Before or After step fails, the report counts that failing step as an extra step. So if you have 5 steps and everything passes, you get 5 total steps of which 5 are passing reported. But if a hidden step fails in that same scenario, then you get 6 total steps, 5 of which are passing and 1 failing in your report.

Since I notice that you're busy lately I went ahead and made a PR. If you can accept this solution then please merge :)

Edit: but of course I'll need permission to be able to push my changes

**Comment by leinonen** [comment]
Sounds good. But I cannot find the PR ?

**Comment by thevictor13** [comment]
Yes.. could not push it as I have no privileges o do so
