### ISSUE TITLE
Getting reporter.create is not a function error

### ISSUE THREAD

**Issue by arunktrk** [leinonen/cucumber-html-report#72]
In my **hooks.js** I placed the below code

  this.After(function(scenario) {
   var reporter = require('cucumber-html-reporter');
     var opts = {
           source:       './report1.json',
            dest:         './',
            name:         'report.html',
            title:        'Cucumber Report',
          }
          reporter.create(opts)
    });

After the execution in report1.json getting the error message as:

"errorMsg": "reporter.create is not a function",
"stackTrace": "TypeError: reporter.create is not a function\n    at World.<anonymous> (C:\\Users\\xxxxxxx\\Desktop\\demo\\setup\\hooks.js:15:20)\n    at _combinedTickCallback (internal/process/next_tick.js:73:7)\n    at process._tickCallback (internal/process/next_tick.js:104:9)"

Can you help me to get the html report.

**Comment by leinonen** [comment]
```javascript
report.create(opts)
  .then(console.log) // You need to run then to trigger the promise
```

**Comment by arunktrk** [comment]
Oops sorry for the wrong module name, Now I can able to see the report. Thanks for the update.
