### ISSUE TITLE
New Feature: disable auto sort scenario by status+name.

### ISSUE THREAD

**Issue by pantherqin** [leinonen/cucumber-html-report#74]
By default the scenarios in each feature are sorted by status before generating the report. Is it possible to provide an option to disable this?

**Comment by Mathieu265** [comment]
I added this PR that add this feature. Waiting for it to be merged.
https://github.com/leinonen/cucumber-html-report/pull/75

**Comment by Mathieu265** [comment]
@pantherqin If you still need this feature you can update to 0.6.1 and set the sortReport option to false, it should work.

**Comment by pantherqin** [comment]
@Mathieu265 Thank you! This feature is really helpful :smile:

**Comment by pantherqin** [comment]
https://github.com/leinonen/cucumber-html-report/pull/75
