### ISSUE TITLE
Cumcumber report generation date

### ISSUE THREAD

**Issue by WasfaKanwal** [leinonen/cucumber-html-report#76]
Hi Leinonen,

That would be great to have date when report was generated (at top of report).
It will be possible for me to use it as test report.
Regards,

Kanwal

**Comment by leinonen** [comment]
Hi Wasfa :)

I will look into it sometime this week.

**Comment by leinonen** [comment]
Fixed. Try version 0.6.2 :)

**Comment by WasfaKanwal** [comment]
Thanks! 
That was quick :)

/WK
